apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vllms.vllm.ai
spec:
  group: vllm.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                  description: "Kubernetes namespace for the vLLM model"
                runtimeName:
                  type: string
                  description: "Name of the vLLM runtime or model"
                replicas:
                  type: integer
                  minimum: 0
                  nullable: true
                  description: "Number of replicas for the model (optional)"
                model:
                  type: string
                  description: "Model name (e.g., meta-llama/Llama-2-7b-hf)"
                storageUri:
                  type: string
                  description: "Model storage path (e.g., s3://bucket/models)"
                args:
                  type: array
                  items:
                    type: string
                  description: "vLLM runtime arguments (e.g., --max-model-len=512)"
                action:
                  type: string
                  enum: ["start", "stop", "update"]
                  description: "Action to perform on the model"
              required: [namespace, runtimeName, model, action]
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of vLLM (Starting, Running, Stopped, Updating, etc)"
                message:
                  type: string
                  description: "Status message"
                startTime:
                  type: string
                  format: "date-time"
                  description: "Timestamp when the current phase started"
                endpoint:
                  type: string
                  description: "Service endpoint (e.g., http://llama-2-7b.default.svc.cluster.local:8000)"
                currentReplicas:
                  type: integer
                  description: "Current number of running replicas"
                condition:
                  type: object
                  description: "Status condition"
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                        description: "Condition type"
                      status:
                        type: string
                        description: "Status of the condition, one of True, False, Unknown"
                      lastTransitionTime:
                        type: string
                        format: "date-time"
                        description: "Last time the condition transitioned from one status to another"
                      reason:
                        type: string
                        description: "Reason for the condition's last transition"
                      message:
                        type: string
                        description: "Human-readable message indicating details about last transition"
      subresources:
        status: {}  # Enable status subresource for proper status updates
  scope: Namespaced
  names:
    plural: vllms
    singular: vllm
    kind: VLLM
    shortNames:
      - vllm